/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 walking.glb --typescript --transform
Files: walking.glb [6.15MB] > C:\Users\slaba\Documents\LostSpace\server\LostSpaceServer\react\public\models\heroAnimations\walking-transformed.glb [633.08KB] (90%)
*/

// gltfjsx model.glb --types --transform

import React, { useMemo } from 'react';
import { useGraph } from '@react-three/fiber';
import { useGLTF, useAnimations } from '@react-three/drei';
import { SkeletonUtils } from 'three-stdlib';
import * as THREE from 'three';

export function HeroWalkingModel({ isMoving, scale }: any) {
  const group = React.useRef<THREE.Group>(null);
  const { scene, animations } = useGLTF('/models/heroAnimations/walking-transformed.glb');
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone) as any;

  // сбросим позицию анимаций на ноль
  const filteredClips = useMemo(() => {
    return animations.map((clip) => {
      const tracks = clip.tracks.filter((t) => !t.name.endsWith('.position'));
      return new THREE.AnimationClip(clip.name, clip.duration, tracks);
    });
  }, [animations]);

  const { actions } = useAnimations(filteredClips, group);

  React.useEffect(() => {
    if (!actions['mixamo.com']) return;
    actions['mixamo.com'].play().setEffectiveTimeScale(0.1);
    if (isMoving) {
      actions['mixamo.com'].play().setEffectiveTimeScale(1);
    }
  }, [isMoving, actions]);
  return (
    <group ref={group} dispose={null} scale={scale}>
      <group name="Root_Scene">
        <group name="RootNode">
          <primitive object={nodes.mixamorigHips} />
        </group>
        <skinnedMesh
          name="temp"
          geometry={nodes.temp.geometry}
          material={materials['Material.001']}
          skeleton={nodes.temp.skeleton}
          scale={100}
        />
      </group>
    </group>
  );
}
useGLTF.preload('/walking-transformed.glb');
